/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParaBaresRouteImport } from './routes/para-bares'
import { Route as IndexRouteImport } from './routes/index'

const ParaBaresRoute = ParaBaresRouteImport.update({
  id: '/para-bares',
  path: '/para-bares',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/para-bares': typeof ParaBaresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/para-bares': typeof ParaBaresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/para-bares': typeof ParaBaresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/para-bares'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/para-bares'
  id: '__root__' | '/' | '/para-bares'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParaBaresRoute: typeof ParaBaresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/para-bares': {
      id: '/para-bares'
      path: '/para-bares'
      fullPath: '/para-bares'
      preLoaderRoute: typeof ParaBaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParaBaresRoute: ParaBaresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
